### ISSUE TITLE
Support unsorted keys

### ISSUE THREAD

**Issue by vbkaisetsu** [daac-tools/crawdad#30]
We often want to use unsorted search patterns, such as hashmap keys, but if we try to build a trie with such a pattern set, we get an error message, and the operation fails.

It is inconvenient to sort a pattern set every time, so it is necessary to address unsorted pattern sets.

**Comment by kampersanda** [comment]
@vbkaisetsu 

Yes, and we have several manners of implementing that function.
The best approach that I think is to implement `insert` and `finish` functions in the `Builder ` class and make it public.
What do you think about this approach?

**Comment by kampersanda** [comment]
Or, we add `needs_sort` flag to `Trie::from_keys`.
On my second thought, this approach is simpler and better.

**Comment by vbkaisetsu** [comment]
I don't think adding options or functions only for unsorted pattern sets is a good idea.
It would be more convenient to allow trie construction from a set of keys, with or without sorting, by a consistent method.
